import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { depot } from '@/data';
import type { LigneBalance, LigneGrandLivre } from '@/data/depot';
import { messageErreur } from '@/data/depot';
import { useDossier } from '@/dossier/DossierProvider';

type Onglet = 'balance' | 'grand-livre';
const tnd = new Intl.NumberFormat('fr-TN', { minimumFractionDigits: 3, maximumFractionDigits: 3 });

export default function Editions() {
  const { dossier, exercice, chargement } = useDossier();
  const [onglet, setOnglet] = useState<Onglet>('balance');
  const [rechercheBalance, setRechercheBalance] = useState('');
  const [classe, setClasse] = useState('');
  const [compteId, setCompteId] = useState('');
  const [rechercheLivre, setRechercheLivre] = useState('');

  const { data: balance = [], isLoading: balanceEnCours, error: erreurBalance } = useQuery({
    queryKey: ['balance', exercice?.id], enabled: Boolean(exercice), queryFn: () => depot.balanceGenerale(exercice!.id),
  });
  const { data: comptes = [] } = useQuery({
    queryKey: ['comptes', dossier?.id], enabled: Boolean(dossier), queryFn: () => depot.listerComptes(dossier!.id),
  });
  const { data: livre = [], isLoading: livreEnCours, error: erreurLivre } = useQuery({
    queryKey: ['grand-livre', exercice?.id, compteId], enabled: Boolean(exercice), queryFn: () => depot.grandLivre(exercice!.id, compteId || undefined),
  });

  const balanceFiltree = useMemo(() => filtrerBalance(balance, rechercheBalance, classe), [balance, rechercheBalance, classe]);
  const livreFiltre = useMemo(() => {
    const terme = rechercheLivre.trim().toLocaleLowerCase('fr');
    return !terme ? livre : livre.filter((ligne) => [ligne.piece_numero, ligne.compte_numero, ligne.compte_libelle, ligne.journal_code, ligne.libelle, ligne.tiers_code ?? ''].join(' ').toLocaleLowerCase('fr').includes(terme));
  }, [livre, rechercheLivre]);

  if (chargement) return <p className="text-sm text-neutral-500">Chargement des éditions…</p>;
  if (!dossier || !exercice) return <p className="text-sm text-neutral-500">Sélectionnez un dossier et un exercice pour afficher les éditions.</p>;

  return <div className="space-y-6"><section><p className="text-xs font-medium uppercase tracking-[0.16em] text-emerald-700 dark:text-emerald-400">Éditions</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-neutral-950 dark:text-white">Balance et grand livre</h1><p className="mt-1 text-sm text-neutral-500">{dossier.raison_sociale} · exercice {exercice.annee}. Les écritures en brouillon sont signalées dans le grand livre.</p></section>
    <div className="flex gap-1 border-b border-neutral-200 dark:border-neutral-800"><Onglet actif={onglet === 'balance'} choisir={() => setOnglet('balance')}>Balance générale</Onglet><Onglet actif={onglet === 'grand-livre'} choisir={() => setOnglet('grand-livre')}>Grand livre</Onglet></div>
    {onglet === 'balance' ? <Balance contenu={balanceFiltree} tout={balance} chargement={balanceEnCours} erreur={erreurBalance ? messageErreur(erreurBalance) : null} recherche={rechercheBalance} setRecherche={setRechercheBalance} classe={classe} setClasse={setClasse} exporter={() => exporterBalance(balanceFiltree, exercice.annee)} /> : <GrandLivre contenu={livreFiltre} comptes={comptes} chargement={livreEnCours} erreur={erreurLivre ? messageErreur(erreurLivre) : null} compteId={compteId} setCompteId={setCompteId} recherche={rechercheLivre} setRecherche={setRechercheLivre} exporter={() => exporterLivre(livreFiltre, exercice.annee)} />}
  </div>;
}

function Balance({ contenu, tout, chargement, erreur, recherche, setRecherche, classe, setClasse, exporter }: { contenu: LigneBalance[]; tout: LigneBalance[]; chargement: boolean; erreur: string | null; recherche: string; setRecherche: (valeur: string) => void; classe: string; setClasse: (valeur: string) => void; exporter: () => void }) {
  const totaux = contenu.reduce((acc, ligne) => ({ debit: acc.debit + Number(ligne.debit), credit: acc.credit + Number(ligne.credit), solde: acc.solde + Number(ligne.solde) }), { debit: 0, credit: 0, solde: 0 });
  const ecart = totaux.debit - totaux.credit;
  return <section className="space-y-4"><div className="flex flex-wrap gap-3 rounded-lg border border-neutral-200 bg-white p-3 dark:border-neutral-800 dark:bg-neutral-900"><input value={recherche} onChange={(e) => setRecherche(e.target.value)} placeholder="Rechercher un compte ou un libellé" className="min-w-60 flex-1 rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100 dark:border-neutral-700 dark:bg-neutral-950" /><select value={classe} onChange={(e) => setClasse(e.target.value)} className="rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-950"><option value="">Toutes les classes</option>{[1, 2, 3, 4, 5, 6, 7, 8].map((numero) => <option key={numero} value={numero}>Classe {numero}</option>)}</select><button type="button" disabled={contenu.length === 0} onClick={exporter} className="rounded-md border border-neutral-300 px-3 py-2 text-sm font-medium hover:bg-neutral-50 disabled:opacity-50 dark:border-neutral-700 dark:hover:bg-neutral-800">Exporter CSV</button></div>
    <div className="grid gap-3 sm:grid-cols-4"><Carte libelle="Comptes mouvementés" valeur={String(tout.length)} /><Carte libelle="Total débit" valeur={`${tnd.format(totaux.debit)} TND`} /><Carte libelle="Total crédit" valeur={`${tnd.format(totaux.credit)} TND`} /><Carte libelle="Équilibre" valeur={Math.abs(ecart) < 0.001 ? 'Équilibrée' : `Écart ${tnd.format(ecart)}`} ton={Math.abs(ecart) < 0.001 ? 'vert' : 'rouge'} /></div>
    {erreur ? <Alerte>{erreur}</Alerte> : chargement ? <p className="text-sm text-neutral-500">Calcul de la balance…</p> : <div className="overflow-hidden rounded-lg border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="overflow-x-auto"><table className="w-full min-w-[770px] border-collapse text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase tracking-wide text-neutral-500 dark:bg-neutral-950/50"><tr><th className="px-4 py-3">Compte</th><th className="px-4 py-3">Libellé</th><th className="px-4 py-3">Classe</th><th className="px-4 py-3 text-right">Débit</th><th className="px-4 py-3 text-right">Crédit</th><th className="px-4 py-3 text-right">Solde</th><th className="px-4 py-3 text-right">Mouv.</th></tr></thead><tbody>{contenu.map((ligne) => <tr key={ligne.compte_id} className="border-t border-neutral-200 dark:border-neutral-800"><td className="px-4 py-2.5 font-mono font-medium">{ligne.compte_numero}</td><td className="px-4 py-2.5">{ligne.compte_libelle}</td><td className="px-4 py-2.5 text-neutral-500">{ligne.compte_classe}</td><Montant valeur={ligne.debit} /><Montant valeur={ligne.credit} /><Montant valeur={ligne.solde} fort /><td className="px-4 py-2.5 text-right font-mono">{ligne.nb_mouvements}</td></tr>)}{contenu.length === 0 && <tr><td colSpan={7} className="px-4 py-12 text-center text-sm text-neutral-500">Aucun mouvement pour ce filtre.</td></tr>}</tbody><tfoot><tr className="border-t-2 border-neutral-900 font-semibold dark:border-neutral-100"><td colSpan={3} className="px-4 py-3">Totaux</td><Montant valeur={totaux.debit} /><Montant valeur={totaux.credit} /><Montant valeur={totaux.solde} fort /><td /></tr></tfoot></table></div></div>}
  </section>;
}

function GrandLivre({ contenu, comptes, chargement, erreur, compteId, setCompteId, recherche, setRecherche, exporter }: { contenu: LigneGrandLivre[]; comptes: { id: string; numero: string; libelle: string }[]; chargement: boolean; erreur: string | null; compteId: string; setCompteId: (valeur: string) => void; recherche: string; setRecherche: (valeur: string) => void; exporter: () => void }) {
  return <section className="space-y-4"><div className="flex flex-wrap gap-3 rounded-lg border border-neutral-200 bg-white p-3 dark:border-neutral-800 dark:bg-neutral-900"><select value={compteId} onChange={(e) => setCompteId(e.target.value)} className="min-w-64 rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-950"><option value="">Tous les comptes</option>{comptes.map((compte) => <option key={compte.id} value={compte.id}>{compte.numero} — {compte.libelle}</option>)}</select><input value={recherche} onChange={(e) => setRecherche(e.target.value)} placeholder="Rechercher une pièce, un tiers, un libellé…" className="min-w-60 flex-1 rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100 dark:border-neutral-700 dark:bg-neutral-950" /><button type="button" disabled={contenu.length === 0} onClick={exporter} className="rounded-md border border-neutral-300 px-3 py-2 text-sm font-medium hover:bg-neutral-50 disabled:opacity-50 dark:border-neutral-700 dark:hover:bg-neutral-800">Exporter CSV</button></div>
    {erreur ? <Alerte>{erreur}</Alerte> : chargement ? <p className="text-sm text-neutral-500">Chargement du grand livre…</p> : <div className="overflow-hidden rounded-lg border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] border-collapse text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase tracking-wide text-neutral-500 dark:bg-neutral-950/50"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Journal</th><th className="px-4 py-3">Pièce</th><th className="px-4 py-3">Compte</th><th className="px-4 py-3">Tiers</th><th className="px-4 py-3">Libellé</th><th className="px-4 py-3 text-right">Débit</th><th className="px-4 py-3 text-right">Crédit</th><th className="px-4 py-3 text-right">Solde cumulé</th></tr></thead><tbody>{contenu.map((ligne) => <tr key={ligne.ecriture_id} className="border-t border-neutral-200 dark:border-neutral-800"><td className="px-4 py-2.5 font-mono">{ligne.date_piece}</td><td className="px-4 py-2.5 font-mono">{ligne.journal_code}</td><td className="px-4 py-2.5"><span className="font-mono">{ligne.piece_numero}</span>{ligne.piece_statut === 'brouillon' && <span className="ml-2 rounded bg-amber-100 px-1.5 py-0.5 text-xs text-amber-800 dark:bg-amber-950 dark:text-amber-300">brouillon</span>}</td><td className="px-4 py-2.5"><span className="font-mono">{ligne.compte_numero}</span><span className="ml-2 text-neutral-500">{ligne.compte_libelle}</span></td><td className="px-4 py-2.5 font-mono">{ligne.tiers_code ?? '—'}</td><td className="px-4 py-2.5">{ligne.libelle}</td><Montant valeur={ligne.debit} /><Montant valeur={ligne.credit} /><Montant valeur={ligne.solde_cumule} fort /></tr>)}{contenu.length === 0 && <tr><td colSpan={9} className="px-4 py-12 text-center text-sm text-neutral-500">Aucun mouvement dans le grand livre.</td></tr>}</tbody></table></div></div>}
  </section>;
}

function filtrerBalance(lignes: LigneBalance[], recherche: string, classe: string) { const terme = recherche.trim().toLocaleLowerCase('fr'); return lignes.filter((ligne) => (!classe || ligne.compte_classe === Number(classe)) && (!terme || `${ligne.compte_numero} ${ligne.compte_libelle}`.toLocaleLowerCase('fr').includes(terme))); }
function exporterBalance(lignes: LigneBalance[], annee: number) { telechargerCsv(`balance-${annee}.csv`, ['Compte', 'Libellé', 'Classe', 'Débit', 'Crédit', 'Solde', 'Mouvements'], lignes.map((ligne) => [ligne.compte_numero, ligne.compte_libelle, ligne.compte_classe, ligne.debit, ligne.credit, ligne.solde, ligne.nb_mouvements])); }
function exporterLivre(lignes: LigneGrandLivre[], annee: number) { telechargerCsv(`grand-livre-${annee}.csv`, ['Date', 'Journal', 'Pièce', 'Statut', 'Compte', 'Libellé compte', 'Tiers', 'Libellé', 'Débit', 'Crédit', 'Solde cumulé'], lignes.map((ligne) => [ligne.date_piece, ligne.journal_code, ligne.piece_numero, ligne.piece_statut, ligne.compte_numero, ligne.compte_libelle, ligne.tiers_code ?? '', ligne.libelle, ligne.debit, ligne.credit, ligne.solde_cumule])); }
function telechargerCsv(nom: string, entetes: string[], lignes: unknown[][]) { const echapper = (valeur: unknown) => `"${String(valeur ?? '').replace(/"/g, '""')}"`; const texte = `\uFEFF${[entetes, ...lignes].map((ligne) => ligne.map(echapper).join(';')).join('\r\n')}`; const url = URL.createObjectURL(new Blob([texte], { type: 'text/csv;charset=utf-8' })); const lien = document.createElement('a'); lien.href = url; lien.download = nom; lien.click(); URL.revokeObjectURL(url); }
function Onglet({ actif, choisir, children }: { actif: boolean; choisir: () => void; children: string }) { return <button type="button" onClick={choisir} className={`border-b-2 px-3 py-2 text-sm font-medium ${actif ? 'border-emerald-700 text-emerald-800 dark:text-emerald-400' : 'border-transparent text-neutral-500 hover:text-neutral-900 dark:hover:text-white'}`}>{children}</button>; }
function Montant({ valeur, fort = false }: { valeur: number; fort?: boolean }) { return <td className={`px-4 py-2.5 text-right font-mono tabular ${fort ? 'font-semibold' : ''}`}>{tnd.format(Number(valeur))}</td>; }
function Carte({ libelle, valeur, ton = 'neutre' }: { libelle: string; valeur: string; ton?: 'neutre' | 'vert' | 'rouge' }) { const fond = ton === 'vert' ? 'border-emerald-200 bg-emerald-50 dark:border-emerald-900 dark:bg-emerald-950/30' : ton === 'rouge' ? 'border-red-200 bg-red-50 dark:border-red-900 dark:bg-red-950/30' : 'border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900'; return <div className={`rounded-lg border p-3 ${fond}`}><p className="text-xs uppercase tracking-wide text-neutral-500">{libelle}</p><p className="mt-1 font-semibold tabular">{valeur}</p></div>; }
function Alerte({ children }: { children: string }) { return <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-950 dark:bg-red-950/40 dark:text-red-300">{children}</p>; }
