/**
 * Données initiales pour le Plan Comptable Tunisien (SYSCOHADA révisé)
 * et les configurations par défaut des contrôles.
 */

import { Compte, SeuilControle } from './types';

export const SEUILS_CONTROLE_DEFAUT: SeuilControle = {
  variationChargeProduit: 15, // ±15%
  seuilImmoCompte615: 500, // 500 DT
  anciennetePassageMois: 3, // > 3 mois
  ancienneteCreanceDetteJours: 90, // > 90 jours
  joursStockLent: 365, // > 365 jours
};

export const INITIAL_ACCOUNTS: Compte[] = [
  // ==========================================
  // CLASSE 1 : COMPTES DE CAPITAUX (Cycle K/L/M)
  // ==========================================
  {
    id: 'c-101',
    numero: '101000',
    libelle: 'Capital social',
    libelleCourt: 'Capital',
    classe: 1,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'CP.01', // Capitaux Propres
    rubriqueLiasse: 'F6002-01', // Capitaux Propres dans F6002
    cycleAudit: 'K',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-106',
    numero: '106000',
    libelle: 'Réserves légales et statutaires',
    libelleCourt: 'Réserves',
    classe: 1,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'CP.02',
    rubriqueLiasse: 'F6002-03',
    cycleAudit: 'K',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-110',
    numero: '110000',
    libelle: 'Report à nouveau',
    libelleCourt: 'Report à nouv',
    classe: 1,
    type: 'Passif',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'CP.03',
    rubriqueLiasse: 'F6002-05',
    cycleAudit: 'K',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-120',
    numero: '120000',
    libelle: 'Résultat net de l\'exercice (Bénéfice/Solde Créditeur)',
    libelleCourt: 'Résultat N',
    classe: 1,
    type: 'Passif',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'CP.04',
    rubriqueLiasse: 'F6002-08',
    cycleAudit: 'K',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-150',
    numero: '150000',
    libelle: 'Provisions pour risques et charges',
    libelleCourt: 'Prov risques',
    classe: 1,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.03', // Passifs non courants - Provisions
    rubriqueLiasse: 'F6002-15',
    cycleAudit: 'L',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-162',
    numero: '162000',
    libelle: 'Emprunts auprès des établissements de crédit',
    libelleCourt: 'Emprunts LT',
    classe: 1,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.01', // Passifs non courants - Emprunts
    rubriqueLiasse: 'F6002-12',
    cycleAudit: 'M',
    bloque: false,
    actif: true,
  },

  // ==========================================
  // CLASSE 2 : COMPTES D'ACTIF IMMOBILISÉ (Cycle C/D/E)
  // ==========================================
  {
    id: 'c-211',
    numero: '211000',
    libelle: 'Frais de recherche et développement',
    libelleCourt: 'Frais R&D',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.01', // Immo incorporelles
    rubriqueLiasse: 'F6001-01',
    cycleAudit: 'C',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-218',
    numero: '218200',
    libelle: 'Logiciels informatiques et assimilés',
    libelleCourt: 'Logiciels',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 4,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.01',
    rubriqueLiasse: 'F6001-02',
    cycleAudit: 'C',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-221',
    numero: '221000',
    libelle: 'Bâtiments industriels et commerciaux',
    libelleCourt: 'Bâtiments',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.02', // Immo corporelles
    rubriqueLiasse: 'F6001-05',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-223',
    numero: '223000',
    libelle: 'Matériel, outillage et équipement industriel',
    libelleCourt: 'Matériel Ind',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.02',
    rubriqueLiasse: 'F6001-06',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-224',
    numero: '224000',
    libelle: 'Matériel de transport (véhicules)',
    libelleCourt: 'Mat Transport',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.02',
    rubriqueLiasse: 'F6001-07',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-228',
    numero: '228300',
    libelle: 'Matériel de bureau et informatique',
    libelleCourt: 'Mat Bureau',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 4,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.02',
    rubriqueLiasse: 'F6001-08',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-230',
    numero: '230000',
    libelle: 'Immobilisations corporelles en cours',
    libelleCourt: 'Immo en cours',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.03', // Immo en cours
    rubriqueLiasse: 'F6001-11',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-250',
    numero: '250000',
    libelle: 'Titres de participation',
    libelleCourt: 'Titres part',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.04', // Immo financières
    rubriqueLiasse: 'F6001-14',
    cycleAudit: 'E',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-281',
    numero: '281000',
    libelle: 'Amortissements des immobilisations incorporelles',
    libelleCourt: 'Amort Incorp',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.05', // Soustraction de l'actif
    rubriqueLiasse: 'F6001-20',
    cycleAudit: 'C',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-282',
    numero: '282000',
    libelle: 'Amortissements des immobilisations corporelles',
    libelleCourt: 'Amort Corp',
    classe: 2,
    type: 'Actif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.06', // Soustraction de l'actif
    rubriqueLiasse: 'F6001-21',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },

  // ==========================================
  // CLASSE 3 : COMPTES DE STOCKS (Cycle F)
  // ==========================================
  {
    id: 'c-311',
    numero: '311000',
    libelle: 'Stocks de matières premières',
    libelleCourt: 'Stocks Mat P',
    classe: 3,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.08', // Stocks
    rubriqueLiasse: 'F6001-24',
    cycleAudit: 'F',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-355',
    numero: '355000',
    libelle: 'Stocks de produits finis',
    libelleCourt: 'Stocks Prod F',
    classe: 3,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.08',
    rubriqueLiasse: 'F6001-26',
    cycleAudit: 'F',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-391',
    numero: '391000',
    libelle: 'Provisions pour dépréciation des stocks',
    libelleCourt: 'Prov Stocks',
    classe: 3,
    type: 'Actif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.09', // Soustraction stocks
    rubriqueLiasse: 'F6001-29',
    cycleAudit: 'F',
    bloque: false,
    actif: true,
  },

  // ==========================================
  // CLASSE 4 : COMPTES DE TIERS (Cycle G/H/I/N/O/P)
  // ==========================================
  {
    id: 'c-401',
    numero: '401000',
    libelle: 'Fournisseurs d\'exploitation',
    libelleCourt: 'Fournisseurs',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: true,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.04', // Passifs courants - Fournisseurs
    rubriqueLiasse: 'F6002-20',
    cycleAudit: 'N',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-408',
    numero: '408000',
    libelle: 'Fournisseurs - Factures non parvenues',
    libelleCourt: 'FNP',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: true,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.04',
    rubriqueLiasse: 'F6002-21',
    cycleAudit: 'N',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-409',
    numero: '409100',
    libelle: 'Fournisseurs - Avances et acomptes versés',
    libelleCourt: 'Fourn Avances',
    classe: 4,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 4,
    collectif: true,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.12', // Autres actifs courants
    rubriqueLiasse: 'F6001-38',
    cycleAudit: 'N',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-411',
    numero: '411000',
    libelle: 'Clients',
    libelleCourt: 'Clients',
    classe: 4,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: true,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.10', // Clients
    rubriqueLiasse: 'F6001-31',
    cycleAudit: 'G',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-419',
    numero: '419100',
    libelle: 'Clients - Avances et acomptes reçus',
    libelleCourt: 'Clients Avanc',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 4,
    collectif: true,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.05', // Autres passifs courants
    rubriqueLiasse: 'F6002-25',
    cycleAudit: 'G',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-421',
    numero: '421000',
    libelle: 'Personnel - Rémunérations dues (Salaires net à payer)',
    libelleCourt: 'Personnel net',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.05',
    rubriqueLiasse: 'F6002-28',
    cycleAudit: 'H',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-432',
    numero: '432000',
    libelle: 'État - Retenues à la source à reverser',
    libelleCourt: 'État RS reverse',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.05',
    rubriqueLiasse: 'F6002-29',
    cycleAudit: 'I',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-4366',
    numero: '436600',
    libelle: 'État - TVA déductible',
    libelleCourt: 'TVA déductible',
    classe: 4,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 4,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.12', // Autres actifs courants
    rubriqueLiasse: 'F6001-41',
    cycleAudit: 'I',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-4367',
    numero: '436700',
    libelle: 'État - TVA collectée',
    libelleCourt: 'TVA collectée',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 4,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.05',
    rubriqueLiasse: 'F6002-30',
    cycleAudit: 'I',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-441',
    numero: '441000',
    libelle: 'État - Impôt sur les bénéfices à reverser',
    libelleCourt: 'État IS',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: true,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.05',
    rubriqueLiasse: 'F6002-31',
    cycleAudit: 'I',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-451',
    numero: '451000',
    libelle: 'Associés, Comptes courants',
    libelleCourt: 'CCA Associés',
    classe: 4,
    type: 'Passif',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'P.05',
    rubriqueLiasse: 'F6002-32',
    cycleAudit: 'O',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-471',
    numero: '471000',
    libelle: 'Comptes d\'attente et de passage',
    libelleCourt: 'Compte d\'attent',
    classe: 4,
    type: 'Actif',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.12',
    rubriqueLiasse: 'F6001-45',
    cycleAudit: 'P',
    bloque: false,
    actif: true,
  },

  // ==========================================
  // CLASSE 5 : TRÉSORERIE (Cycle J)
  // ==========================================
  {
    id: 'c-512',
    numero: '512000',
    libelle: 'Banques locales (en devises ou TND)',
    libelleCourt: 'Banque',
    classe: 5,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: true,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.14', // Liquidités et équivalents
    rubriqueLiasse: 'F6001-52',
    cycleAudit: 'J',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-531',
    numero: '531000',
    libelle: 'Caisse principale TND',
    libelleCourt: 'Caisse',
    classe: 5,
    type: 'Actif',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.14',
    rubriqueLiasse: 'F6001-54',
    cycleAudit: 'J',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-585',
    numero: '585000',
    libelle: 'Virements internes de fonds',
    libelleCourt: 'Virem Internes',
    classe: 5,
    type: 'Actif',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: true,
    rapprochable: false,
    reportRan: 'detail',
    deviseCompte: 'TND',
    rubriqueBilan: 'A.14',
    rubriqueLiasse: 'F6001-55',
    cycleAudit: 'J',
    bloque: false,
    actif: true,
  },

  // ==========================================
  // CLASSE 6 : CHARGES D'EXPLOITATION, FINANCIÈRES (Cycles H/I/N/S/R)
  // ==========================================
  {
    id: 'c-601',
    numero: '601000',
    libelle: 'Achats consommés de matières premières',
    libelleCourt: 'Achats Cons MP',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.05', // Charges d'exploitation - Achats consommés
    rubriqueLiasse: 'F6003-05',
    cycleAudit: 'N',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-603',
    numero: '603000',
    libelle: 'Variations des stocks de matières premières',
    libelleCourt: 'Var stock mat',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.04', // Variation de stocks consommés
    rubriqueLiasse: 'F6003-04',
    cycleAudit: 'F',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-615',
    numero: '615000',
    libelle: 'Entretien et réparations d\'immobilisations et matériels',
    libelleCourt: 'Entretien répar',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.06', // Services extérieurs
    rubriqueLiasse: 'F6003-08',
    cycleAudit: 'D', // Lié aux immo
    bloque: false,
    actif: true,
  },
  {
    id: 'c-641',
    numero: '641000',
    libelle: 'Charges de personnel (Salaires bruts)',
    libelleCourt: 'Salaires bruts',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.07', // Charges de personnel
    rubriqueLiasse: 'F6003-12',
    cycleAudit: 'H',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-651',
    numero: '651000',
    libelle: 'Charges financières (Intérêts d\'emprunts)',
    libelleCourt: 'Intérêts Empr',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.10', // Charges financières
    rubriqueLiasse: 'F6003-20',
    cycleAudit: 'S',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-661',
    numero: '661000',
    libelle: 'Impôts et taxes d\'exploitation (TFP, FOPROLOS...)',
    libelleCourt: 'Taxes explo',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.08', // Impôts et taxes d'exploitation
    rubriqueLiasse: 'F6003-15',
    cycleAudit: 'I',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-6811',
    numero: '681100',
    libelle: 'Dotations aux amortissements des immobilisations corporelles',
    libelleCourt: 'Dotat Amort C',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 4,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.09', // Dotations
    rubriqueLiasse: 'F6003-18',
    cycleAudit: 'D',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-691',
    numero: '691000',
    libelle: 'Impôt sur les bénéfices des sociétés (I.S.)',
    libelleCourt: 'Impôts Soc IS',
    classe: 6,
    type: 'Charge',
    natureSolde: 'Debiteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.14', // Impôt bénéfices
    rubriqueLiasse: 'F6003-35',
    cycleAudit: 'I',
    bloque: false,
    actif: true,
  },

  // ==========================================
  // CLASSE 7 : PRODUITS D'EXPLOITATION, FINANCIERS (Cycles G/S/R)
  // ==========================================
  {
    id: 'c-701',
    numero: '701000',
    libelle: 'Ventes de produits finis (Local)',
    libelleCourt: 'Ventes Prod L',
    classe: 7,
    type: 'Produit',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.01', // Produits d'exploitation - Ventes
    rubriqueLiasse: 'F6003-01',
    cycleAudit: 'G',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-703',
    numero: '703000',
    libelle: 'Ventes de produits finis à l\'exportation',
    libelleCourt: 'Ventes Export',
    classe: 7,
    type: 'Produit',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.01',
    rubriqueLiasse: 'F6003-02',
    cycleAudit: 'G',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-713',
    numero: '713000',
    libelle: 'Variations des stocks de produits finis et en cours',
    libelleCourt: 'Var stock prod',
    classe: 7,
    type: 'Produit',
    natureSolde: 'Solde',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.02', // Variation de stocks de produits
    rubriqueLiasse: 'F6003-03',
    cycleAudit: 'F',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-736',
    numero: '736000',
    libelle: 'Gains de cession d\'immobilisations',
    libelleCourt: 'Gains cession',
    classe: 7,
    type: 'Produit',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.13', // Gains et profits extraordinaires / de cession
    rubriqueLiasse: 'F6003-24',
    cycleAudit: 'R',
    bloque: false,
    actif: true,
  },
  {
    id: 'c-751',
    numero: '751000',
    libelle: 'Produits financiers (Intérêts, gains de change)',
    libelleCourt: 'Prod Financiers',
    classe: 7,
    type: 'Produit',
    natureSolde: 'Crediteur',
    niveau: 3,
    collectif: false,
    lettrable: false,
    rapprochable: false,
    reportRan: 'solde',
    deviseCompte: 'TND',
    rubriqueCr: 'R.11', // Produits financiers
    rubriqueLiasse: 'F6003-22',
    cycleAudit: 'S',
    bloque: false,
    actif: true,
  },
];
